name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  go_version: 1.19
  yq_version: v4.27.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/${{ env.yq_version }}/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod a+x /usr/local/bin/yq

      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract tag version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        shell: bash

      - name: Extract repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Set zip file env name
        run: echo "ZIP_NAME=${{env.REPOSITORY_NAME}}.zip" >> $GITHUB_ENV

      - name: Generate manifest versioned file
        run: |
          echo -e "plugin:\n  version: $VERSION" > manifest.version.yml

      - name: Merge manifest.yml with manifest.version.yml
        run: yq ea '. as $item ireduce ({}; . * $item )' manifest.yml manifest.version.yml

      - name: Build and Package
        shell: bash
        run: make zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          draft: true
          generate_release_notes: true
          files: |
            build/${{ env.ZIP_NAME }}
            README.md